### ISSUE TITLE
Support iOS 12?

### ISSUE THREAD

**Issue by drager** [curityio/ios-idsvr-haapi-sdk-dist#1]
Hey! Is there any specific reason why you don't support iOS 12? iPhone 6 for example are using iOS 12.5.5 and we would like to support that phone, but would be unable to do so by using your lib.

**Comment by mtrojanowski** [comment]
Hey @drager, yes there is a reason. The authentication API driver uses hardware attestation to make sure that the application is run on a genuine Apple device. This is to make sure that no one just takes your code and uses it to log in users by impersonating your app. The attestation features were only introduced in iOS 14. That's why the driver requires at least that version of iOS. You can read more about the security of HAAPI and the importance of attestation in this whitepaper: https://curity.io/resources/documents/hypermedia-authentication-api-security-in-detail-whitepaper 

For devices with iOS < 14 you would have to provide a fallback that uses the regular app-auth flows, something like described here: https://curity.io/resources/learn/swift-ios-appauth/

**Comment by drager** [comment]
> Hey @drager, yes there is a reason. The authentication API driver uses hardware attestation to make sure that the application is run on a genuine Apple device. This is to make sure that no one just takes your code and uses it to log in users by impersonating your app. The attestation features were only introduced in iOS 14. That's why the driver requires at least that version of iOS. You can read more about the security of HAAPI and the importance of attestation in this whitepaper: https://curity.io/resources/documents/hypermedia-authentication-api-security-in-detail-whitepaper
> 
> For devices with iOS < 14 you would have to provide a fallback that uses the regular app-auth flows, something like described here: https://curity.io/resources/learn/swift-ios-appauth/

I see! Thanks for answering!
